language: generic
git:
  depth: false
  submodules: false
script:
# download build library
- git clone --depth=1 --branch=master https://github.com/dragon-lang/buildlib.git ../buildlib
# Make sure our iso command works
- ../buildlib/iso dmd-build
- ../buildlib/iso ldc-build
# build dmd using ldc (NOT WORKING RIGHT NOW)
# TODO: override generate directory
#- ../buildlib/iso ldc-build ./src/build.d HOST_DMD=ldmd2
# build dmd using dmd
#- rm -rf generated/linux
- ../buildlib/iso dmd-build ./src/build.d
# build druntime and phobos.
- git clone --depth=1 --branch=master https://github.com/dlang/druntime.git ../druntime
- git clone --depth=1 --branch=master https://github.com/dlang/phobos.git ../phobos
- ../buildlib/iso dmd-build make -j$(nproc) -C ../druntime -f posix.mak DMD=../dc/generated/linux/release/64/dmd DMD_DIR=../dc CC=$(which gcc)
- ../buildlib/iso dmd-build make -j$(nproc) -C ../phobos -f posix.mak DMD=../dc/generated/linux/release/64/dmd DMD_DIR=../dc CC=$(which gcc)
# run unittest and testsuite.
#make -j$(nproc) -C ../druntime -f posix.mak DMD=../dc/generated/linux/release/64/dmd unittest
#make -j$(nproc) -C ../phobos -f posix.mak DMD=../dc/generated/linux/release/64/dmd unittest
#make -j$(nproc) -C test DMD=../dc/generated/linux/release/64/dmd MODEL=64
# run the dmd test suite
- ../buildlib/iso dmd-test ./test/run.d
