language: d
git:
  depth: false
  submodules: false
before_script:
# gdb is used by some dmd tests
- sudo apt-get install gdb
script:
# install rund
- git clone --depth=1 --branch=master https://github.com/marler8997/rund.git ../rund
- dmd -I../rund/src -run ../rund/make.d build
- sudo cp ../rund/bin/rund /bin/rund
# build dmd
- ./src/build.d
# build druntime and phobos.
- git clone --depth=1 --branch=master https://github.com/dlang/druntime.git ../druntime
- git clone --depth=1 --branch=master https://github.com/dlang/phobos.git ../phobos
- make -j$(nproc) -C ../druntime -f posix.mak DMD=../dc/generated/linux/release/64/dmd DMD_DIR=../dc
- make -j$(nproc) -C ../phobos -f posix.mak DMD=../dc/generated/linux/release/64/dmd DMD_DIR=../dc
# run unittest and testsuite.
#make -j$(nproc) -C ../druntime -f posix.mak DMD=../dc/generated/linux/release/64/dmd unittest
#make -j$(nproc) -C ../phobos -f posix.mak DMD=../dc/generated/linux/release/64/dmd unittest
#make -j$(nproc) -C test DMD=../dc/generated/linux/release/64/dmd MODEL=64
# run the dmd test suite
- dmd -run test/run.d
